export const KEYBOARD_UPDATE = 'KEYBOARD_UPDATE';
export const ALERT_PUSH = 'ALERT_PUSH';
export const ALERT_REMOVE = 'ALERT_REMOVE';

export const USER_UPDATE = 'USER_UPDATE';

export const WALLETS_ADD = 'WALLETS_ADD';
export const WALLETS_SET_LOADING = 'WALLETS_SET_LOADING';
export const WALLETS_CHANGE_CURRENCY = 'WALLETS_CHANGE_CURRENCY';
export const WALLETS_LIST_UPDATE = 'WALLETS_LIST_UPDATE';

export const CURRENCIES_INIT = 'CURRENCIES_INIT';
export const CURRENCIES_UPDATE = 'CURRENCIES_UPDATE';
export const CURRENCIES_SET_EXCHANGE = 'CURRENCIES_SET_EXCHANGE';
export const CURRENCIES_SET_LIST = 'CURRENCIES_SET_LIST';
export const CURRENCIES_SET_LIST_REVISION = 'CURRENCIES_SET_LIST_REVISION';

export const MENU_UPDATE = 'MENU_UPDATE';

export const NAV_UPDATE_STATE= 'NAV_UPDATE_STATE';

export const LOADING_LOADED_CLEAR = 'LOADING_LOADED_CLEAR';
export const LOADING_LOADED_REMOVE = 'LOADING_LOADED_REMOVE';
export const LOADING_LOADED_ADD = 'LOADING_LOADED_ADD';
